-LC:\borland\bcc55\lib\obj;C:\borland\bcc55\lib;C:\develop\xharbour\1.2.3\lib -Gn -M -m -s -Tpe -x -aa +
c0w32.obj obj\winrent.obj obj\collrep.obj obj\conprt.obj obj\enquire.obj obj\errorsys.obj obj\itemrep.obj obj\maincont.obj obj\mainitem.obj obj\mainowne.obj obj\mainperi.obj obj\mainsite.obj obj\maintran.obj obj\maintruc.obj obj\mediexpo.obj obj\mediimpo.obj obj\miscrep.obj obj\newtruck.obj obj\printfunc.obj obj\proclib.obj obj\pulsarex.obj obj\setupdbf.obj obj\tranrep.obj obj\utilback.obj obj\arglexpo.obj obj\utillabe.obj obj\utilpack.obj obj\utilsppa.obj obj\utilstoc.obj, +
winrent.exe,, +
lang.lib vm.lib rtl.lib rdd.lib macro.lib pp.lib dbfntx.lib dbfcdx.lib dbffpt.lib common.lib           gtwvw.lib codepage.lib ct.lib tip.lib pcrepos.lib hsx.lib hbsix.lib zlib.lib telepath.lib import32.lib cw32.lib, +
, +
winrent.res
